package dev.taypeer

import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.setValue
import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import dev.taypeer.bridge.PasswordOptions
import dev.taypeer.bridge.generatePassword
import dev.taypeer.bridge.generatePassphrase
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext

/** Form is retained only in memory across configuration changes; never in saved state. */
class GeneratorState : ViewModel() {
    var passphrase by mutableStateOf(false)
    var length by mutableStateOf("30")
    var words by mutableStateOf("6")
    var separator by mutableStateOf("-")
    var uppercase by mutableStateOf(true)
    var lowercase by mutableStateOf(true)
    var digits by mutableStateOf(true)
    var punctuation by mutableStateOf(true)
    var excludeSimilar by mutableStateOf(false)
    var exclusions by mutableStateOf("")
    var generated by mutableStateOf("")
        private set
    var error by mutableStateOf(false)
    var running by mutableStateOf(false)
        private set
    var revealed by mutableStateOf(false)
    private var generation = 0L

    fun generate() {
        val count = if (passphrase) words.toUByteOrNull()?.toUShort() else length.toUShortOrNull()
        if (count == null) { error = true; return }
        val phrase = passphrase
        val join = separator
        val options = PasswordOptions(count, uppercase, lowercase, digits, punctuation, excludeSimilar, exclusions)
        val request = ++generation
        running = true
        error = false
        viewModelScope.launch {
            try {
                val value = withContext(Dispatchers.Default) {
                    if (phrase) generatePassphrase(count.toUByte(), join) else generatePassword(options)
                }
                if (generation == request) { generated = value; revealed = false }
            } catch (_: Exception) { if (generation == request) error = true }
            finally { if (generation == request) running = false }
        }
    }
    fun lock() {
        ++generation
        generated = ""
        revealed = false
        running = false
        error = false
    }
    override fun onCleared() { lock() }
}
